<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bc0b7d38-e3db-4001-bb34-d97bd9015398</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfilePath>../../Dockerfile</DockerfilePath>
    <DockerfileContext>../..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Ecommerce.Application/Ecommerce.Application.csproj" />
    <ProjectReference Include="../Ecommerce.Infrastructure/Ecommerce.Infrastructure.csproj" />
  </ItemGroup>

</Project>
